### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by Jdahl13** [SufferPal/sufferpal-frontend#21]
13 
* Stats recorded from activities

Sessions:

Calories
Start time
Max cadence
Min heart rate
Avg speed
Max heart rate
Total moving time
Total distance
Avg cadence
Total calories
Sport
Avg heart rate

Record:

Timestamp
Position - lat and long
Distance
Speed
Altitude
Cadence
Heart rate

**Comment by danielpencak** [comment]
We have gathered all of the data necessary from the fit file. However we are currently working on uploading the array of records to DynamoBD through the GraphQL api.
