### ISSUE TITLE
Setup Endpoint for sprint 3

### ISSUE THREAD

**Issue by Thesawr** [SufferPal/sufferpal-frontend#46]
Finish activity endpoints

- add description to activity table [X]

Finish user endpoints

- add settings to user table [X]

- stats and personal records [Moving to sprint 4]

- add uploaded image to S3 and store key in user table [X]

21 pts

**Comment by danielpencak** [comment]
For the time being we should be able to use the endpoints created by Amplify but in the next sprint we may want to refine them if time permits.
