### ISSUE TITLE
Create Profile Page UI Mockup

### ISSUE THREAD

**Issue by danielpencak** [SufferPal/sufferpal-frontend#58]

**Comment by jmikrut08** [comment]
[https://files.slack.com/files-pri/T011UR5MRGD-F014B24JVTN/sufferpal_timeline_nocolumns.jpg](url)

**Comment by jmikrut08** [comment]
![sufferpal copy](https://user-images.githubusercontent.com/42018754/82721382-abcd4d80-9c8a-11ea-86ac-c73cbeab3243.jpg)
